# Generated by Django 5.0.4 on 2024-04-10 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.BooleanField(verbose_name='غرق شده')),
                ('pclass', models.PositiveIntegerField(choices=[(1, 'First class'), (2, 'Second class'), (3, 'Third class')], verbose_name='کلاس بلیت')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='جنسیت')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)], verbose_name='سن')),
                ('sibsp', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='تعداد همسر و خواهر و برادر ')),
                ('parch', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='تعداد فرزندان و پدر و مادر ')),
                ('ticket', models.CharField(max_length=20, verbose_name='کد بلیت')),
                ('fare', models.FloatField(verbose_name='کرایه(پوند)')),
                ('cabin', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره کابین')),
                ('embarked', models.CharField(choices=[('S', 'southhampton'), ('C', 'sherburg'), ('Q', 'queentown')], verbose_name='بندر سوار شده')),
            ],
        ),
    ]
