# Generated by Django 5.0.4 on 2024-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cabin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کابین'),
        ),
    ]
